### ISSUE TITLE
My device is bricked after flashing. How to debrick it?

### ISSUE THREAD

**Issue by Blue-Beaker** [HungThinhIT/X96Q_AndroidTV_Root_and_Restore_Firmware_Method#1]
After flashing, my X96Q 2G/16G is bricked and stuck at the x96q logo screen.

I've backed up my boot partition before flashing boot, but it was useless since I can't access adb under this situation.

The PhoenixSuit tool doesn't recognize the boot partition images, so I downloaded full stock image but it stucks at Beginning Firmware Upgrade: 0 min 0 s after the device is plugged in.

**Comment by kripper** [comment]
What was you mistake?

**Comment by Blue-Beaker** [comment]
I pushed downloaded boot image to the device via adb, and flashed it with the given commands, then it stucks at "X96Q" screen after rebooting. I have sent it back to the seller to fix it.
